# Generated by Django 3.1.6 on 2021-02-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tencetcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=128, verbose_name='order')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
                ('title', models.CharField(max_length=500, verbose_name='url')),
                ('fee', models.BigIntegerField(verbose_name='fee')),
                ('cout', models.BigIntegerField(verbose_name='cout')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '腾讯课堂',
                'verbose_name_plural': '腾讯课堂',
            },
        ),
    ]
