# Generated by Django 3.1.6 on 2021-02-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tencetcourse',
            name='create_date',
        ),
    ]
