# Generated by Django 3.1.6 on 2021-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_tencetcourse_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuyuzhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=128, verbose_name='order')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('link', models.CharField(max_length=500, verbose_name='link')),
            ],
            options={
                'verbose_name': 'fuyuzhe',
                'verbose_name_plural': 'fuyuzhe',
            },
        ),
        migrations.AlterField(
            model_name='tencetcourse',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
