# Generated by Django 3.1.6 on 2021-02-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='每一笔款项描述', max_length=128, verbose_name='收支项')),
                ('salary', models.BigIntegerField(verbose_name='金额')),
                ('pay', models.BigIntegerField(verbose_name='金额')),
                ('cost', models.BigIntegerField(verbose_name='金额')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '收支',
                'verbose_name_plural': '收支记录',
            },
        ),
        migrations.CreateModel(
            name='ChartByModel',
            fields=[
            ],
            options={
                'verbose_name': 'ChartByModel',
                'verbose_name_plural': 'ChartByModel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.money',),
        ),
        migrations.CreateModel(
            name='ChartBySql',
            fields=[
            ],
            options={
                'verbose_name': 'ChartBySQL',
                'verbose_name_plural': 'ChartBySQL',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.money',),
        ),
        migrations.CreateModel(
            name='TestChart1',
            fields=[
            ],
            options={
                'verbose_name': 'TestChart1',
                'verbose_name_plural': 'TestChart1',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.money',),
        ),
        migrations.CreateModel(
            name='TestChart2',
            fields=[
            ],
            options={
                'verbose_name': 'TestChart2',
                'verbose_name_plural': 'TestChart2',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.money',),
        ),
        migrations.CreateModel(
            name='TestControl',
            fields=[
            ],
            options={
                'verbose_name': 'TestControl',
                'verbose_name_plural': 'TestControl',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.money',),
        ),
    ]
